//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossBeeze.CrossTest.Process.PowerCenter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7333/wsh/services/BatchServices/DataIntegration")]
        public string CrossBeeze_CrossTest_Process_PowerCenter_PowerCenterWebService_DataIntegrationService {
            get {
                return ((string)(this["CrossBeeze_CrossTest_Process_PowerCenter_PowerCenterWebService_DataIntegrationSer" +
                    "vice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:7333/wsh/services/BatchServices/DataIntegration")]
        public string CrossBeeze_CrossTest_Process_PowerCenter_PowerCenterWebService1_DataIntegrationService {
            get {
                return ((string)(this["CrossBeeze_CrossTest_Process_PowerCenter_PowerCenterWebService1_DataIntegrationSe" +
                    "rvice"]));
            }
        }
    }
}
