# .NET Desktop

# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
    branches:
        include:
        - master
        - develop
        - features/*
        - hotfix/*

    paths:
        exclude:
        - ./CrossTest_Java
        - ./Generation
        - ./Java
        - ./Model
        - ./Old

pool:
  vmImage: 'windows-latest'
  
variables:
  solution: 'CrossBreeze.CrossTest.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  
steps:
- task: NuGetToolInstaller@1
  displayName: Install NuGet

- task: NuGetCommand@2
  displayName: Install required NuGet packages from config
  inputs:
    nugetConfigPath: 'NuGet.config'
    restoreSolution: '$(solution)'

- task: VSBuild@1
  displayName: MsBuild CrossTest Solution (exclude SSIS project)
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Running extremely slow. Not needed yet, so disabled for now
# - task: DevEnvBuild@2
#   displayName: DevEnv Build SSIS Example Project
#   inputs:
#     solution: 'Examples\CrossBreeze_CrossTest_ExampleTests\ProcessSteps\SupportFiles\ExampleSSISProject\ExampleSSISProject.dtproj'
#     vsVersion: 'latest'