// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CrossBreeze.CrossTest.ExampleTests.DatabaseSteps
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DatabaseFunctionTestStepsNLFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "ExampleDatabaseFunctionSteps_NL.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("nl"), "DatabaseSteps", "Database function test steps (NL)", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Database function test steps (NL)")))
            {
                global::CrossBreeze.CrossTest.ExampleTests.DatabaseSteps.DatabaseFunctionTestStepsNLFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
#line 5
 testRunner.Given("de ExampleMsSqlServer database server wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gegeven ");
#line hidden
#line 6
 testRunner.And("de ExampleDatabase database wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
#line 7
 testRunner.And("dat de tabel [dbo].[ExampleStagingTable] leeg is", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Functie uitvoeren")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Database function test steps (NL)")]
        public void FunctieUitvoeren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Functie uitvoeren", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn"});
                table13.AddRow(new string[] {
                            "Some data"});
                table13.AddRow(new string[] {
                            "Some data2"});
#line 10
 testRunner.Given("de staging-storage tabel [dbo].[ExampleStagingTable] met de volgende data geladen" +
                        " wordt:", ((string)(null)), table13, "Gegeven ");
#line hidden
#line 14
 testRunner.When("ik de functie [dbo].[GetExampleStagingTable] uitvoer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn",
                            "StageDateTime"});
                table14.AddRow(new string[] {
                            "Some data",
                            "2000-01-01 00:00:00.00"});
                table14.AddRow(new string[] {
                            "Some data2",
                            "2000-01-01 00:00:00.00"});
#line 15
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table14, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Functie met template uitvoeren")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Database function test steps (NL)")]
        public void FunctieMetTemplateUitvoeren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Functie met template uitvoeren", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn"});
                table15.AddRow(new string[] {
                            "Some data"});
                table15.AddRow(new string[] {
                            "Some data2"});
#line 21
 testRunner.Given("de staging-storage tabel [dbo].[ExampleStagingTable] met de volgende data geladen" +
                        " wordt:", ((string)(null)), table15, "Gegeven ");
#line hidden
#line 25
 testRunner.When("ik de GetExampleStagingTable dbo functie uitvoer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn",
                            "StageDateTime"});
                table16.AddRow(new string[] {
                            "Some data",
                            "2000-01-01 00:00:00.00"});
                table16.AddRow(new string[] {
                            "Some data2",
                            "2000-01-01 00:00:00.00"});
#line 26
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table16, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Functie met parameters uitvoeren")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Database function test steps (NL)")]
        public void FunctieMetParametersUitvoeren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Functie met parameters uitvoeren", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn"});
                table17.AddRow(new string[] {
                            "Some data2"});
#line 32
 testRunner.Given("de staging-storage tabel [dbo].[ExampleStagingTable] met de volgende data geladen" +
                        " wordt:", ((string)(null)), table17, "Gegeven ");
#line hidden
                TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                            "Parameter",
                            "Value"});
                table18.AddRow(new string[] {
                            "ExampleColumn",
                            "\'Some data2\'"});
#line 35
 testRunner.When("ik de functie [dbo].[GetExampleStagingTableWithParameter] uitvoer met de volgende" +
                        " parameter:", ((string)(null)), table18, "Als ");
#line hidden
                TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn",
                            "StageDateTime"});
                table19.AddRow(new string[] {
                            "Some data2",
                            "2000-01-01 00:00:00.00"});
#line 38
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table19, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Functie met template en parameters uitvoeren")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Database function test steps (NL)")]
        public void FunctieMetTemplateEnParametersUitvoeren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Functie met template en parameters uitvoeren", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 42
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn"});
                table20.AddRow(new string[] {
                            "Some data2"});
#line 43
 testRunner.Given("de staging-storage tabel [dbo].[ExampleStagingTable] met de volgende data geladen" +
                        " wordt:", ((string)(null)), table20, "Gegeven ");
#line hidden
                TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                            "Parameter",
                            "Value"});
                table21.AddRow(new string[] {
                            "ExampleColumn",
                            "\'Some data2\'"});
#line 46
 testRunner.When("ik de GetExampleStagingTableWithParameter dbo2 functie uitvoer met de volgende pa" +
                        "rameter:", ((string)(null)), table21, "Als ");
#line hidden
                TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn",
                            "StageDateTime"});
                table22.AddRow(new string[] {
                            "Some data2",
                            "2000-01-01 00:00:00.00"});
#line 49
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table22, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Functie met parameters uit template uitvoeren")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Database function test steps (NL)")]
        public void FunctieMetParametersUitTemplateUitvoeren()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Functie met parameters uit template uitvoeren", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 53
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn"});
                table23.AddRow(new string[] {
                            "Some data2"});
#line 54
 testRunner.Given("de staging-storage tabel [dbo].[ExampleStagingTable] met de volgende data geladen" +
                        " wordt:", ((string)(null)), table23, "Gegeven ");
#line hidden
#line 57
 testRunner.When("ik de GetExampleStagingTableWithParameter dbo2 functie uitvoer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
                TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                            "ExampleColumn",
                            "StageDateTime"});
                table24.AddRow(new string[] {
                            "Some data2",
                            "2000-01-01 00:00:00.00"});
#line 58
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table24, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
