// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CrossBreeze.CrossTest.ExampleTests.ProcessSteps
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RunExampleADFProcesNLFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private static string[] featureTags = new string[] {
                "ADF"};
        
#line 1 "ExampleADFProcessSteps_NL.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("nl"), "ProcessSteps", "Run Example ADF proces (NL)", null, ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Run Example ADF proces (NL)")))
            {
                global::CrossBreeze.CrossTest.ExampleTests.ProcessSteps.RunExampleADFProcesNLFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
 testRunner.Given("de ExampleMsSqlServer database server wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gegeven ");
#line hidden
#line 7
 testRunner.And("de tempdb database wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
#line 8
 testRunner.When("ik de volgende SQL query uitvoer:", "IF (object_ID(\'testTable\') IS NOT NULL)\r\nBEGIN\r\nDROP TABLE testTable\r\nEND\r\n\r\nCREA" +
                    "TE TABLE testTable (id INT, description VARCHAR(50))\r\n\r\ninsert into  [tempdb].[d" +
                    "bo].[testTable] values (1, \'FirstRow\')", ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer ADF proces uit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example ADF proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ADF")]
        public void VoerADFProcesUit()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer ADF proces uit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 20
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 21
 testRunner.When("het CrossTestPipeline ADF proces in het ExampleAdfPipeline project op dit moment " +
                        "wordt uitgevoerd", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
#line 22
 testRunner.And("ik de inhoud van de tabel [dbo].[testTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
                TechTalk.SpecFlow.Table table51 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "description"});
                table51.AddRow(new string[] {
                            "1",
                            "\'FirstRow\'"});
#line 23
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table51, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd ADF proces uit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example ADF proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ADF")]
        public void VoerGetypeerdADFProcesUit()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd ADF proces uit", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 27
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 28
 testRunner.When("het CrossTestPipelineWithParameters adfTemplate ADF proces in het ExampleAdfPipel" +
                        "ine project op dit moment wordt uitgevoerd", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line hidden
#line 29
 testRunner.And("ik de inhoud van de tabel [dbo].[testTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
                TechTalk.SpecFlow.Table table52 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "description"});
                table52.AddRow(new string[] {
                            "1",
                            "\'FirstRow\'"});
#line 30
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table52, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer ADF proces uit met parameters")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example ADF proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ADF")]
        public void VoerADFProcesUitMetParameters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer ADF proces uit met parameters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 34
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table53 = new TechTalk.SpecFlow.Table(new string[] {
                            "Parameter",
                            "Value"});
                table53.AddRow(new string[] {
                            "baseUrl",
                            "https://x-test.nl/"});
                table53.AddRow(new string[] {
                            "uri",
                            "DotNet"});
#line 35
 testRunner.When("het CrossTestPipelineWithParameters ADF proces in het ExampleAdfPipeline project " +
                        "op dit moment wordt uitgevoerd met de volgende parameter:", ((string)(null)), table53, "Als ");
#line hidden
#line 39
 testRunner.And("ik de inhoud van de tabel [dbo].[testTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
                TechTalk.SpecFlow.Table table54 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "description"});
                table54.AddRow(new string[] {
                            "1",
                            "\'FirstRow\'"});
#line 40
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table54, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd ADF proces uit met parameters")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example ADF proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("ADF")]
        public void VoerGetypeerdADFProcesUitMetParameters()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd ADF proces uit met parameters", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 44
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table55 = new TechTalk.SpecFlow.Table(new string[] {
                            "Parameter",
                            "Value"});
                table55.AddRow(new string[] {
                            "uri",
                            "Java"});
#line 45
 testRunner.When("het CrossTestPipelineWithParameters adfTemplate ADF proces in het ExampleAdfPipel" +
                        "ine project op dit moment wordt uitgevoerd met de volgende parameter:", ((string)(null)), table55, "Als ");
#line hidden
#line 48
 testRunner.And("ik de inhoud van de tabel [dbo].[testTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
                TechTalk.SpecFlow.Table table56 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "description"});
                table56.AddRow(new string[] {
                            "1",
                            "\'FirstRow\'"});
#line 49
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table56, "Dan ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
