// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CrossBreeze.CrossTest.ExampleTests.ProcessSteps
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class RunExampleSSISProcesNLFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
#line 1 "ExampleSSISProcessSteps_NL.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("nl"), "Run Example SSIS proces (NL)", null, ProgrammingLanguage.CSharp, new string[] {
                        "SSIS"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "Run Example SSIS proces (NL)")))
            {
                global::CrossBreeze.CrossTest.ExampleTests.ProcessSteps.RunExampleSSISProcesNLFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line 6
 testRunner.Given("de ExampleMsSqlServer database server wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Gegeven ");
#line 7
 testRunner.And("de TestDB database wordt gebruikt", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line 8
 testRunner.And("dat de tabel [dbo].[TestTable] leeg is", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer SSIS proces uit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerSSISProcesUit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer SSIS proces uit", null, ((string[])(null)));
#line 10
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line 11
 testRunner.When("het ExamplePackage SSIS proces in het ExampleSsisISPacProject project op dit mome" +
                    "nt wordt uitgevoerd", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line 12
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table1.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 13
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table1, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd SSIS proces uit")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerGetypeerdSSISProcesUit()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd SSIS proces uit", null, ((string[])(null)));
#line 17
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line 18
 testRunner.When("het ExamplePackage dwh SSIS proces in het ExampleSsisISPacProject project op dit " +
                    "moment wordt uitgevoerd", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line 19
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table2.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 20
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table2, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer SSIS proces uit met parameters")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerSSISProcesUitMetParameters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer SSIS proces uit met parameters", null, ((string[])(null)));
#line 24
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table3.AddRow(new string[] {
                        "ExampleParameter",
                        "SomeParameterValue"});
#line 25
 testRunner.When("het ExamplePackage SSIS proces in het ExampleSsisISPacProject project op dit mome" +
                    "nt wordt uitgevoerd met de volgende parameter:", ((string)(null)), table3, "Als ");
#line 28
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table4.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 29
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table4, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd SSIS proces uit met parameters")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerGetypeerdSSISProcesUitMetParameters()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd SSIS proces uit met parameters", null, ((string[])(null)));
#line 33
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table5.AddRow(new string[] {
                        "ExampleParameter",
                        "SomeParameterValue"});
#line 34
 testRunner.When("het ExamplePackage dwh SSIS proces in het ExampleSsisISPacProject project op dit " +
                    "moment wordt uitgevoerd met de volgende parameter:", ((string)(null)), table5, "Als ");
#line 37
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table6.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 38
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table6, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer SSIS proces uit als rol")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerSSISProcesUitAlsRol()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer SSIS proces uit als rol", null, ((string[])(null)));
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line 43
 testRunner.When("de developer het ExamplePackage SSIS proces in het ExampleSsisISPacProject projec" +
                    "t uitvoert", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line 44
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table7.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 45
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table7, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd SSIS proces uit als rol")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerGetypeerdSSISProcesUitAlsRol()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd SSIS proces uit als rol", null, ((string[])(null)));
#line 49
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line 50
 testRunner.When("de developer het ExamplePackage dwh SSIS proces in het ExampleSsisISPacProject pr" +
                    "oject uitvoert", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Als ");
#line 51
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table8.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 52
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table8, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer SSIS proces uit met parameters als rol")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerSSISProcesUitMetParametersAlsRol()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer SSIS proces uit met parameters als rol", null, ((string[])(null)));
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table9.AddRow(new string[] {
                        "ExampleParameter",
                        "SomeParameterValue"});
#line 57
 testRunner.When("de developer het ExamplePackage SSIS proces in het ExampleSsisISPacProject projec" +
                    "t uitvoert met de volgende parameter:", ((string)(null)), table9, "Als ");
#line 60
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table10.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 61
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table10, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Voer getypeerd SSIS proces uit met parameters als rol")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "Run Example SSIS proces (NL)")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCategoryAttribute("SSIS")]
        public virtual void VoerGetypeerdSSISProcesUitMetParametersAlsRol()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Voer getypeerd SSIS proces uit met parameters als rol", null, ((string[])(null)));
#line 65
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Parameter",
                        "Value"});
            table11.AddRow(new string[] {
                        "ExampleParameter",
                        "SomeParameterValue"});
#line 66
 testRunner.When("de developer het ExamplePackage dwh SSIS proces in het ExampleSsisISPacProject pr" +
                    "oject uitvoert met de volgende parameter:", ((string)(null)), table11, "Als ");
#line 69
 testRunner.And("ik de inhoud van de tabel [dbo].[TestTable] ophaal", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "En ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "description"});
            table12.AddRow(new string[] {
                        "1",
                        "\'FirstRow\'"});
#line 70
 testRunner.Then("verwacht ik het volgende resultaat:", ((string)(null)), table12, "Dan ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
